language:
- node_js:
before_install:
  - npm install -g lerna
  # Repo for Yarn
  - sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
  - echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq yarn
cache:
  yarn: true
install:
  - npm install
  - lerna bootstrap
  - cd packages/aeproject-cli
  - yarn link
  - cd ..
  - cd aeproject-lib
  - npm run tsc
  - cd ../..
services:
  - docker
script:
  - 'docker version'
  - npm test
addons:
  apt:
    packages:
      - docker-ce
env:
  - DOCKER_COMPOSE_VERSION=1.24.1
