version: 2
jobs:
  build:
    docker:
    - image: circleci/node:9.5.0
    branches:
      only:
        - update/migrate-to-circleci
          
    steps:
      - checkout
      - setup_remote_docker
      


      - run:
          command: |
            #sudo rm /usr/local/bin/docker-compose
            set -x
            curl -L https://github.com/docker/compose/releases/download/1.20.0/docker-compose-`uname -s`-`uname -m` > ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose
            sudo npm install -g lerna
            sudo apt-key adv --fetch-keys http://dl.yarnpkg.com/debian/pubkey.gpg
            echo "deb http://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
            sudo apt-get update -qq
            sudo apt-get install -y -qq yarn

     
            


      - run:
          command: |
            sudo npm install
            lerna bootstrap
            cd packages/aeproject-lib
            npm run tsc
            cd ../..
            sudo npm run develop

      # run tests!
      - run: aeproject --version
      - run:
          command: |
            sudo docker info
            #sudo docker rm $(docker ps -a -q)
            #sudo docker info
            ls -la
            mkdir test2
            cd test2
            aeproject init
            ls -la
            set -x
            sudo docker-compose ps
            sudo docker-compose -f docker-compose.yml -f docker-compose.compiler.yml down -v --remove-orphans
            sudo docker-compose -f docker-compose.yml -f docker-compose.compiler.yml up -d
            aeproject node
            aeproject compile
          no_output_timeout: 30m