version: '3'
services:
  node:
    image: 'aeternity/aeternity:${NODE_TAG}'
    hostname: node
    environment:
      AETERNITY_CONFIG: /home/aeternity/aeternity.yaml
    command: |
      bin/aeternity console -noinput -aehttp enable_debug_endpoints true
    volumes:
      - './docker/aeternity.yaml:/home/aeternity/aeternity.yaml'
  proxy:
    image: 'nginx:1.13.8'
    hostname: proxy
    ports:
      - '3001:3001'
    volumes:
      - './docker/nginx.conf:/etc/nginx/conf.d/default.conf'