name: Build and Test

on: [push]

jobs:
  build-and-test:
    strategy:
      matrix:
        node-version: [16, 18, 20, 21]
        node-tag: [latest]
        compiler-tag: [v7.6.1] # latest is v8.0.0-rc1 which is not supported by the sdk currently

        # for lts node also test first known compatible and latest known good compiler and node versions
        include:
          - node-version: 20
            node-tag: v6.8.0 # v6.3.0 to v6.7.0 use a different config format
            compiler-tag: v7.4.0
          - node-version: 20
            node-tag: v6.12.0
            compiler-tag: v7.6.1

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build:clean && npm run build
      - run: npm run lint:ci
      - run: npm test
        env:
          NODE_VERSION: ${{ matrix.node-version }}
          NODE_TAG: ${{ matrix.node-tag }}
          COMPILER_TAG: ${{ matrix.compiler-tag }}
